### ISSUE TITLE
MA启动问题

### ISSUE THREAD

**Issue by liuzhi1986** [uavorg/uavstack#477]
想使用docker部署MA，docker仅启动MA进程。但是部署过程中发现，在非uavagent/bin/目录下执行start.sh脚本都是无法启动MA的，使用run.sh的启动会程序main会抛出空指针异常

`Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
Java HotSpot(TM) 64-Bit Server VM warning: UseCMSCompactAtFullCollection is deprecated and will likely be removed in a future release.
Java HotSpot(TM) 64-Bit Server VM warning: CMSFullGCsBeforeCompaction is deprecated and will likely be removed in a future release.
Exception in thread "main" java.lang.NullPointerException
	at sun.misc.URLClassPath.<init>(URLClassPath.java:112)
	at sun.misc.URLClassPath.<init>(URLClassPath.java:122)
	at java.net.URLClassLoader.<init>(URLClassLoader.java:106)
	at com.creditease.mscp.boot.MSCPBoot$1.run(MSCPBoot.java:164)
	at com.creditease.mscp.boot.MSCPBoot$1.run(MSCPBoot.java:159)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.creditease.mscp.boot.MSCPBoot.createBootClassLoader(MSCPBoot.java:159)
	at com.creditease.mscp.boot.MSCPBoot.start(MSCPBoot.java:129)
	at com.creditease.mscp.boot.MSCPBoot.main(MSCPBoot.java:53)
`

**Comment by liuzhi1986** [comment]
无法随docker运行而运行，只能运行之后再进入容器内启动MA吗？
